### ISSUE TITLE
Improve efficiency photobleaching

### ISSUE THREAD

**Issue by albertmg1** [FLClab/pySTED#27]
Note that the "bleaching" branch albertmg1/pySTED contain improvements to the photobleaching calculation speed, but those improvements require some modifications to the latest version with anthony's "masking" improvement to the photobleaching. Also, the modifications compatibility with dymin was neglected. 

Here are those improvements in the "bleaching" branch.
- The bleaching probability map is only caculated and applied for the region where it is non-null (size of  the psf), instead of the whole datamap (might make a bigger difference for larger images)
- The bleaching probability map is only caculated once if the power does not vary.

I will implement those modifications quickly if I see it makes a big difference in the calculation time for some experiments.

**Comment by antho214** [comment]
[Pull request #27](https://github.com/FLClab/pySTED/pull/28) fixed this issue.
